- name: Write calico-policy-controller yaml
  template: src=calico-policy-controller.yml.j2 dest=/etc/kubernetes/calico-policy-controller.yml
  when: inventory_hostname == groups['kube-master'][0]


- name: Start of Calico policy controller
  kube:
    name: "calico-policy-controller"
    kubectl: "{{bin_dir}}/kubectl"
    filename: "/etc/kubernetes/calico-policy-controller.yml"
    namespace: "kube-system"
    resource: "rs"
  when: inventory_hostname == groups['kube-master'][0]
