---
- hosts: all
  gather_facts: false
  roles:
    - bootstrap-os
  tags:
    - bootstrap-os


- hosts: all
  gather_facts: true

- hosts: etcd:!k8s-cluster
  roles:
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: etcd, tags: etcd }

- hosts: k8s-cluster
  roles:
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: etcd, tags: etcd }
    - { role: kubernetes/node, tags: node }
    - { role: network_plugin, tags: network }

- hosts: kube-master
  roles:
    - { role: kubernetes/preinstall, tags: preinstall }
    - { role: kubernetes/master, tags: master }

- hosts: k8s-cluster
  roles:
    - { role: dnsmasq, tags: dnsmasq }

- hosts: kube-master[0]
  roles:
    - { role: kubernetes-apps, tags: apps }
