---
- src: https://gitlab.com/kubespray-ansibl8s/k8s-common.git
  path: roles/apps
  scm: git

#- src: https://gitlab.com/kubespray-ansibl8s/k8s-dashboard.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-kubedns.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-elasticsearch.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-redis.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-memcached.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-postgres.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-pgbouncer.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-heapster.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-influxdb.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-kubedash.git
#  path: roles/apps
#  scm: git
#
#- src: https://gitlab.com/kubespray-ansibl8s/k8s-kube-logstash.git
#  path: roles/apps
#  scm: git
