apiVersion: v1
kind: Pod
metadata:
  name: netchecker-server
  labels:
    app: netchecker-server
  namespace: {{ netcheck_namespace }}
spec:
  containers:
    - name: netchecker-server
      image: "{{ server_img }}"
      env:
      imagePullPolicy: {{ k8s_image_pull_policy }}
      resources:
        limits:
          cpu: {{ netchecker_server_cpu_limit }}
          memory: {{ netchecker_server_memory_limit }}
        requests:
          cpu: {{ netchecker_server_cpu_requests }}
          memory: {{ netchecker_server_memory_requests }}
      ports:
        - containerPort: 8081
          hostPort: 8081
    - name: kubectl-proxy
      image: "{{ kubectl_image }}"
      imagePullPolicy: {{ k8s_image_pull_policy }}
      resources:
        limits:
          cpu: {{ netchecker_kubectl_cpu_limit }}
          memory: {{ netchecker_kubectl_memory_limit }}
        requests:
          cpu: {{ netchecker_kubectl_cpu_requests }}
          memory: {{ netchecker_kubectl_memory_requests }}
      args:
        - proxy
