# This is where all the cert scripts and certs will be located
kube_cert_dir: "{{ kube_config_dir }}/ssl"

dns_domain: "{{ cluster_name }}"

# resolv.conf to base dns config
kube_resolv_conf: "/etc/resolv.conf"

kube_proxy_mode: iptables

# kube_api_runtime_config:
#   - extensions/v1beta1/daemonsets=true
#   - extensions/v1beta1/deployments=true
